easy_admin:
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Produit
            form:
                fields: ['productName', 'productDescription', 'price', 'isPublished', 'imageName', 'category', 'publisher']
        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
        Tag:
            class: App\Entity\Tag
    user:
        display_name: true
    design:
        brand_color: '#000'
