easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Produit
        - App\Entity\Category
        - App\Entity\User
        - App\Entity\Tag
    user:
        display_name: true
    design:
        brand_color: '#000'
