twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: 
        - 'bootstrap_4_layout.html.twig'
        #- 'templates/materialize_layout.html.twig' #Ne marche pas =(, enfin je n'arrive pas a le faire marcher
