create:
  path: /create
  controller: App\Controller\ProductController::create
  methods: ['GET', 'POST']
update:
  path: /update/{slug}
  controller: App\Controller\ProductController::update
  requirements:
    slug: '[a-z0-9\-]+'
  methods: ['GET', 'POST']
delete:
  path: /suppression/jesuissur/delete/{slug}
  controller: App\Controller\ProductController::delete
  requirements:
    slug: '[a-z0-9\-]+'
  methods: ['GET', 'POST']
